server:
  port: 9092
  
spring:
  application:
    name: USER-SERVICE
    
  datasource:
    url: jdbc:postgresql://localhost:5432/hms?serverTimezone=UTC
    username: postgres
    password: abhishek123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/        
